[[enums]]
name = "someEnum"
# type = int
values = ["x", "y", "z"]

[[structs]]
name = "foobar"
fields = [
    {name = "i", type = "u32"},
    {name = "j", type = "u32"},
]

[[structs]]
name = "MoveComponent"
component = true
fields = [
    {name = "id", type = "u32"},
    {name = "flag", type = "bool"},
    #{name = "c", type = "vec3"},
    #{name = "d", type = "someEnum"},
    #{name = "e", type = "foobar"},
    #{name = "f", type = "foobar[32]"}, # array
    #{name = "g", type = "foobar[]"}, # vector
    #{name = "h", type = "foobar[string]"}, # map
]