[enums]
[enums.someEnum]
# type = int
values = ["x", "y", "z"]

[structs]
[structs.foobar]
i = "u32"
j = "u32"

[structs.MoveComponent]
a = "u32"
b = "bool"
c = "vec3"
d = "someEnum"
e = "foobar"
f = "foobar[32]" # array
g = "foobar[]" # vector
h = "foobar[string]" # map

[structs.MoveComponent2]
component = true
fields = [
    {name = "a", type = "u32"},
    {name = "b", type = "bool"},
    {name = "c", type = "vec3"},
    {name = "d", type = "someEnum"},
    {name = "e", type = "foobar"},
    {name = "f", type = "foobar[32]"}, # array
    {name = "g", type = "foobar[]"}, # vector
    {name = "h", type = "foobar[string]"}, # map
]